const roles = {
baron: <span className="role"><img src="../images/laneIcons/laneBaron.webp" alt="Baron lane icon" /> Baron</span>,
jungle: <span className="role"><img src="../images/laneIcons/laneJungle.webp" alt="Jungle lane icon" /> Jungle</span>,
middle: <span className="role"><img src="../images/laneIcons/laneMiddle.webp" alt="Middle lane icon" /> Middle</span>,
duo: <span className="role"><img src="../images/laneIcons/laneDuo.webp" alt="Duo lane icon" /> Duo</span>,
support: <span className="role"><img src="../images/laneIcons/laneSupport.webp" alt="Support lane icon" /> Support</span>
}

const champions = [
 {
    name: 'Aatrox',
    title: 'the Darkin Blade',
    icon: '../images/portraits/AatroxSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 600,
    healthScale: 95,
    manaBase: false,
    armorBase: 40,
    armorScale: 4,
    magresBase: 40,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 62,
    attackScale: 4,
    apBase: 0,
    asBase: 0.664,
    asBaseBonus: 0.664*0.1,
    asScale: 0.664*0.012
  },

{
    name: 'Ahri',
    title: 'The Nine-Tailed Fox',
    icon: '../images/portraits/AhriSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 530,
    healthScale: 78,
    manaBase: 435,
    manaScale: 37,
    armorBase: 30,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 52,
    attackScale: 3,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0
  },

{
    name: 'Akali',
    title: 'The Rogue Assasin',
    icon: '../images/portraits/AkaliSquare.webp',
    rolePrim: roles.middle,
    roleSecond: roles.baron,
    healthBase: 600,
    healthScale: 93,
    manaBase: false,
    manaScale: 0,
    armorBase: 34,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 64,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

{
    name: 'Akshan',
    title: 'The Rogue Sentinel',
    icon: '../images/portraits/AkshanSquare.webp',
    rolePrim: roles.middle,
    roleSecond: roles.duo,
    healthBase: 570,
    healthScale: 86,
    manaBase: 390,
    manaScale: 37,
    armorBase: 35,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 52,
    attackScale: 5,
    apBase: 0,
    asBase: 0.5,
    asBaseBonus: 0.5*0.4,
    asScale: 0.5*0.007
  },

{
    name: 'Alistar',
    title: 'The Minotaur',
    icon: '../images/portraits/AlistarSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 610,
    healthScale: 100,
    manaBase: 345,
    manaScale: 31,
    armorBase: 45,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 340,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

{
    name: 'Amumu',
    title: 'The Sad Mummy',
    icon: '../images/portraits/AmumuSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: roles.support,
    healthBase: 650,
    healthScale: 71,
    manaBase: 390,
    manaScale: 49,
    armorBase: 35,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 345,
    attackBase: 52,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

{
    name: 'Annie',
    title: 'The Dark Child',
    icon: '../images/portraits/AnnieSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 530,
    healthScale: 96,
    manaBase: 435,
    manaScale: 43,
    armorBase: 30,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 52,
    attackScale: 2,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0
  },

{
    name: 'Ashe',
    title: 'The Frost Archer',
    icon: '../images/portraits/AsheSquare.webp',
    rolePrim: roles.duo,
    roleSecond: roles.support,
    healthBase: 570,
    healthScale: 76,
    manaBase: 345,
    manaScale: 30,
    armorBase: 35,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 335,
    attackBase: 58,
    attackScale: 2,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.667*0.33,
    asScale: 0.667*0.032
  },

  {
    name: 'Aurelion Sol',
    title: 'The Star Forger',
    icon: '../images/portraits/Aurelion_SolSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 86,
    manaBase: 435,
    manaScale: 43,
    armorBase: 30,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 335,
    attackBase: 52,
    attackScale: 2,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0
  },

  {
    name: 'Blitzcrank',
    title: 'The Great Steam Golem',
    icon: '../images/portraits/BlitzcrankSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 650,
    healthScale: 86,
    manaBase: 300,
    manaScale: 31,
    armorBase: 50,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 335,
    attackBase: 58,
    attackScale: 2,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Brand',
    title: 'The Burning Vengeance',
    icon: '../images/portraits/BrandSquare.webp',
    rolePrim: roles.middle,
    roleSecond: roles.support,
    healthBase: 530,
    healthScale: 71,
    manaBase: 435,
    manaScale: 37,
    armorBase: 30,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0
  },

  {
    name: 'Braum',
    title: 'The Heart of the Freljord',
    icon: '../images/portraits/BraumSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 686,
    healthScale: 71,
    manaBase: 300,
    manaScale: 37,
    armorBase: 46,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 345,
    attackBase: 54,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Caitlyn',
    title: 'The Sheriff of Piltover',
    icon: '../images/portraits/CaitlynSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 570,
    healthScale: (86),
    manaBase: 345,
    manaScale: 31,
    armorBase: 35,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 335,
    attackBase: 54,
    attackScale: 4,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.032
  },

  {
    name: 'Camille',
    title: 'The Steel Shadow',
    icon: '../images/portraits/CamilleSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 650,
    healthScale: 120,
    manaBase: 390,
    manaScale: 25,
    armorBase: 40,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.624*0.23,
    asScale: 0.667*0.022
  },

  {
    name: 'Corki',
    title: 'The Daring Bombardier',
    icon: '../images/portraits/CorkiSquare.webp',
    rolePrim: roles.duo,
    roleSecond: roles.middle,
    healthBase: 570,
    healthScale: 112,
    manaBase: 435,
    manaScale: 50,
    armorBase: 35,
    armorScale: 4,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 335,
    attackBase: 52,
    attackScale: 3,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022
  },

  {
    name: 'Darius',
    title: 'The Hand of Noxus',
    icon: '../images/portraits/DariusSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 610,
    healthScale: 136,
    manaBase: 345,
    manaScale: 31,
    armorBase: 45,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 70,
    attackScale: 5,
    apBase: 0,
    asBase: 0.664,
    asBaseBonus: 0.664*0.13,
    asScale: 0.664*0.012
  },

  {
    name: 'Diana',
    title: 'The Scorn of the Moon',
    icon: '../images/portraits/DianaSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 600,
    healthScale: 93,
    manaBase: 435,
    manaScale: 31,
    armorBase: 40,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 52,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Dr. Mundo',
    title: 'The Madman of Zaun',
    icon: '../images/portraits/DrMundoSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 78,
    manaBase: false,
    manaScale: 0,
    armorBase: 35,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Draven',
    title: 'The Glorious Executioner',
    icon: '../images/portraits/DravenSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 610,
    healthScale: 86,
    manaBase: 480,
    manaScale: 49,
    armorBase: 35,
    armorScale: 4,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 66,
    attackScale: 4,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.032
  },

  {
    name: 'Ekko',
    title: 'The Boy Who Shattered Time',
    icon: '../images/portraits/EkkoSquare.webp',
    rolePrim: roles.middle,
    roleSecond: roles.jungle,
    healthBase: 610,
    healthScale: 78,
    manaBase: 390,
    manaScale: 43,
    armorBase: 40,
    armorScale: 3,
    magresBase: 38,
    magresScale: 4,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Evelynn',
    title: 'Agony\'s Embrace',
    icon: '../images/portraits/EvelynnSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 610,
    healthScale: 78,
    manaBase: 390,
    manaScale: 43,
    armorBase: 40,
    armorScale: 3,
    magresBase: 38,
    magresScale: 4,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Ezreal',
    title: 'The Prodigal Explorer',
    icon: '../images/portraits/EzrealSquare.webp',
    rolePrim: roles.duo,
    roleSecond: roles.middle,
    healthBase: 570,
    healthScale: 78,
    manaBase: 390,
    manaScale: 37,
    armorBase: 30,
    armorScale: 4,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 335,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.022
  },

  {
    name: 'Fiora',
    title: 'The Grand Duelist',
    icon: '../images/portraits/FioraSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 610,
    healthScale: 115,
    manaBase: 300,
    manaScale: 37,
    armorBase: 40,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 70,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Fizz',
    title: 'The Tidal Trickster',
    icon: '../images/portraits/FizzSquare.webp',
    rolePrim: roles.middle,
    roleSecond: roles.jungle,
    healthBase: 610,
    healthScale: 93,
    manaBase: 345,
    manaScale: 37,
    armorBase: 30,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Galio',
    title: 'The Colossus',
    icon: '../images/portraits/GalioSquare.webp',
    rolePrim: roles.middle,
    roleSecond: roles.support,
    healthBase: 570,
    healthScale: 100,
    manaBase: 435,
    manaScale: 25,
    armorBase: 30,
    armorScale: 3,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Garen',
    title: 'The Might of Demacia',
    icon: '../images/portraits/GarenSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 650,
    healthScale: 93,
    manaBase: false,
    manaScale: 0,
    armorBase: 45,
    armorScale: 5,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 64,
    attackScale: 5,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Gragas',
    title: 'The Rabble Rouser',
    icon: '../images/portraits/GragasSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 86,
    manaBase: 390,
    manaScale: 43,
    armorBase: 40,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 340,
    attackBase: 70,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Graves',
    title: 'The Outlaw',
    icon: '../images/portraits/GravesSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: roles.baron,
    healthBase: 570,
    healthScale: 86,
    manaBase: 390,
    manaScale: 37,
    armorBase: 35,
    armorScale: 3,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 64,
    attackScale: 3,
    apBase: 0,
    asBase: 1,
    asBaseBonus: 1*0.03,
    asScale: 1*0.022
  },

  {
    name: 'Gwen',
    title: 'The Hallowed Seamstress',
    icon: '../images/portraits/GwenSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 660,
    healthScale: 86,
    manaBase: 345,
    manaScale: 31,
    armorBase: 45,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 340,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.23,
    asScale: 0.667*0.022
  },
  
  {
    name: 'Hecarim',
    title: 'The Shadow of War',
    icon: '../images/portraits/HecarimSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 630,
    healthScale: 89,
    manaBase: 380,
    manaScale: 43,
    armorBase: 37,
    armorScale: 4,
    magresBase: 36,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },
  
  {
    name: 'Irelia',
    title: 'The Blade Dancer',
    icon: '../images/portraits/IreliaSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.middle,
    healthBase: 650,
    healthScale: 86,
    manaBase: 345,
    manaScale: 25,
    armorBase: 40,
    armorScale: 3,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Janna',
    title: 'The Storm\'s Fury',
    icon: '../images/portraits/JannaSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 570,
    healthScale: 71,
    manaBase: 435,
    manaScale: 43,
    armorBase: 40,
    armorScale: 4,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 361,
    attackBase: 52,
    attackScale: 2,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0
  },


  {
    name: 'Jarvan IV',
    title: 'The Exemplar of Demacia',
    icon: '../images/portraits/JarvanIVSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 650,
    healthScale: 86,
    manaBase: 390,
    manaScale: 31,
    armorBase: 40,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },  
  
  {
    name: 'Jax',
    title: 'Grandmaster at Arms',
    icon: '../images/portraits/JaxSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 112,
    manaBase: 390,
    manaScale: 43,
    armorBase: 40,
    armorScale: 3,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.664,
    asBaseBonus: 0.664*0.13,
    asScale: 0.664*0.022
  },

  {
    name: 'Jayce',
    title: 'The Defender of Tomorrow',
    icon: '../images/portraits/JayceSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.middle,
    healthBase: 610,
    healthScale: 78,
    manaBase: 345,
    manaScale: 43,
    armorBase: 40,
    armorScale: 4,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 345,
    attackBase: 54,
    attackScale: 4,
    apBase: 0,
    asBase: 0.669,
    asBaseBonus: 0.669*0.36,
    asScale: 0.669*0.032
  },

  {
    name: 'Jhin',
    title: 'The Virtuoso',
    icon: '../images/portraits/JhinSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 570,
    healthScale: 86,
    manaBase: 390,
    manaScale: 43,
    armorBase: 35,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.629,
    asBaseBonus: 0.629*0.05,
    asScale: 0.629*0.032
  },

  {
    name: 'Jinx',
    title: 'The Loose Cannon',
    icon: '../images/portraits/JinxSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 610,
    healthScale: 78,
    manaBase: 345,
    manaScale: 37,
    armorBase: 35,
    armorScale: 4,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 335,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.017
  },

  {
    name: 'Kai\'Sa',
    title: 'Daughter of the Void',
    icon: '../images/portraits/KaisaSquare.webp',
    rolePrim: roles.duo,
    roleSecond: roles.middle,
    healthBase: 570,
    healthScale: 86,
    manaBase: 435,
    manaScale: 31,
    armorBase: 35,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 62,
    attackScale: 3,
    apBase: 0,
    asBase: 0.626,
    asBaseBonus: 0.626*0.23,
    asScale: 0.626*0.032
  },

  {
    name: 'Karma',
    title: 'The Enlightened One',
    icon: '../images/portraits/KarmaSquare.webp',
    rolePrim: roles.support,
    roleSecond: roles.middle,
    healthBase: 570,
    healthScale: 93,
    manaBase: 390,
    manaScale: 43,
    armorBase: 35,
    armorScale: 4,
    magresBase: 32,
    magresScale: 1,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022
  },

  {
    name: 'Kassadin',
    title: 'The Void Walker',
    icon: '../images/portraits/KassadinSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 600,
    healthScale: 78,
    manaBase: 480,
    manaScale: 49,
    armorBase: 30,
    armorScale: 3,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Katarina',
    title: 'The Sinister Blade',
    icon: '../images/portraits/KatarinaSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 86,
    manaBase: false,
    manaScale: 0,
    armorBase: 30,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Kayle',
    title: 'The Righteous',
    icon: '../images/portraits/KayleSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.middle,
    healthBase: 570,
    healthScale: 71,
    manaBase: 345,
    manaScale: 31,
    armorBase: 30,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 345,
    attackBase: 52,
    attackScale: 2,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.23,
    asScale: 0.667*0.022
  },

  {
    name: 'Kayn',
    title: 'The Shadow Assasin',
    icon: '../images/portraits/KaynSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 600,
    healthScale: 83,
    manaBase: 420,
    manaScale: 45,
    armorBase: 37,
    armorScale: 4,
    magresBase: 36,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 70,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Kennen',
    title: 'The Heart of the Tempest',
    icon: '../images/portraits/KennenSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.middle,
    healthBase: 610,
    healthScale: 78,
    manaBase: false,
    manaScale: 50,
    armorBase: 40,
    armorScale: 4,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022
  },

  {
    name: 'Kha\'Zix',
    title: 'The Voidreaver',
    icon: '../images/portraits/Kha\'ZixSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 610,
    healthScale: 78,
    manaBase: 390,
    manaScale: 37,
    armorBase: 35,
    armorScale: 3,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 54,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Lee Sin',
    title: 'The Blind Monk',
    icon: '../images/portraits/Lee_SinSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 650,
    healthScale: 78,
    manaBase: false,
    manaScale: 50,
    armorBase: 35,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 66,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Leona',
    title: 'The Radiant Dawn',
    icon: '../images/portraits/LeonaSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 690,
    healthScale: 78,
    manaBase: 390,
    manaScale: 31,
    armorBase: 50,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 345,
    attackBase: 62,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.012
  },

  {
    name: 'Lillia',
    title: 'The Bashful Bloom',
    icon: '../images/portraits/LilliaSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 104,
    manaBase: 420,
    manaScale: 37,
    armorBase: 34,
    armorScale: 3,
    magresBase: 32,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 62,
    attackScale: 2,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022
  },

  {
    name: 'Lucian',
    title: 'The Purifier',
    icon: '../images/portraits/LucianSquare.webp',
    rolePrim: roles.duo,
    roleSecond: roles.middle,
    healthBase: 610,
    healthScale: 86,
    manaBase: 390,
    manaScale: 37,
    armorBase: 35,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 345,
    attackBase: 64,
    attackScale: 3,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.032
  },

  {
    name: 'Lulu',
    title: 'The Fae Sorceress',
    icon: '../images/portraits/LuluSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 530,
    healthScale: 71,
    manaBase: 480,
    manaScale: 43,
    armorBase: 40,
    armorScale: 4,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 46,
    attackScale: 2,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0
  },

  {
    name: 'Lux',
    title: 'The Lady of Luminosity',
    icon: '../images/portraits/LuxSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 530,
    healthScale: 78,
    manaBase: 480,
    manaScale: 37,
    armorBase: 30,
    armorScale: 4,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 52,
    attackScale: 3,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.6625*0
  },

  {
    name: 'Malphite',
    title: 'Shard of the Monolith',
    icon: '../images/portraits/MalphiteSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 650,
    healthScale: 86,
    manaBase: 345,
    manaScale: 31,
    armorBase: 45,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 52,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Master Yi',
    title: 'The Wuju Bladesman',
    icon: '../images/portraits/Master_YiSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 610,
    healthScale: 78,
    manaBase: 345,
    manaScale: 37,
    armorBase: 40,
    armorScale: 3,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 54,
    attackScale: 3,
    apBase: 0,
    asBase: 0.82,
    asScale: 0.014285714
  },

  {
    name: 'Miss Fortune',
    title: 'The Bounty Hunter',
    icon: '../images/portraits/MissFortuneSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 570,
    healthScale: 86,
    manaBase: 390,
    manaScale: 31,
    armorBase: 34,
    armorScale: 4,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 335,
    attackBase: 54,
    attackScale: 3,
    apBase: 0,
    asBase: 0.623,
    asBaseBonus: 0.623*0.3,
    asScale: 0.623*0.032
  },

  {
    name: 'Morgana',
    title: 'The Fallen',
    icon: '../images/portraits/MorganaSquare.webp',
    rolePrim: roles.support,
    roleSecond: roles.middle,
    healthBase: 570,
    healthScale: 78,
    manaBase: 435,
    manaScale: 37,
    armorBase: 35,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 2,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022
  },

  {
    name: 'Nami',
    title: 'The Tidecaller',
    icon: '../images/portraits/NamiSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 570,
    healthScale: 71,
    manaBase: 390,
    manaScale: 37,
    armorBase: 35,
    armorScale: 4,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 345,
    attackBase: 52,
    attackScale: 3,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0
  },

  {
    name: 'Nasus',
    title: 'The Curator of the Sands',
    icon: '../images/portraits/NasusSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 610,
    healthScale: 86,
    manaBase: 390,
    manaScale: 37,
    armorBase: 40,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 66,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Nautilus',
    title: 'The Titan of the Depths',
    icon: '../images/portraits/NautilusSquare.webp',
    rolePrim: roles.support,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 86,
    manaBase: 390,
    manaScale: 43,
    armorBase: 40,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 340,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.664,
    asBaseBonus: 0.664*0.1,
    asScale: 0.664*0.012
  },

  {
    name: 'Nilah',
    title: 'The Joy Unbound',
    icon: '../images/portraits/NilahSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 570,
    healthScale: 83,
    manaBase: 340,
    manaScale: 37,
    armorBase: 37,
    armorScale: 4,
    magresBase: 32,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.669,
    asBaseBonus: 0.669*0.33,
    asScale: 0.669*0.032
  },

  {
    name: 'Nunu & Willump',
    title: 'The Boy and His Yeti',
    icon: '../images/portraits/Nunu_WillumpSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 610,
    healthScale: 112,
    manaBase: 345,
    manaScale: 31,
    armorBase: 35,
    armorScale: 3,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 64,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Olaf',
    title: 'The Berserker',
    icon: '../images/portraits/OlafSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: roles.baron,
    healthBase: 650,
    healthScale: 78,
    manaBase: 340,
    manaScale: 15,
    armorBase: 35,
    armorScale: 3,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 64,
    attackScale: 4,
    apBase: 0,
    asBase: 0.664,
    asBaseBonus: 0.664*0.1,
    asScale: 0.664*0.022
  },

  {
    name: 'Orianna',
    title: 'The Lady of Clockwork',
    icon: '../images/portraits/OriannaSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 530,
    healthScale: 86,
    manaBase: 435,
    manaScale: 43,
    armorBase: 25,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 335,
    attackBase: 46,
    attackScale: 2,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0
  },

  {
    name: 'Ornn',
    title: 'The Fire Below the Mountain',
    icon: '../images/portraits/OrnnSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.support,
    healthBase: 660,
    healthScale: 112,
    manaBase: 380,
    manaScale: 45,
    armorBase: 40,
    armorScale: 4,
    magresBase: 40,
    magresScale: 2,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.664,
    asBaseBonus: 0.664*0.1,
    asScale: 0.664*0.012
  },

  {
    name: 'Pantheon',
    title: 'The Unbreakable Spear',
    icon: '../images/portraits/PantheonSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 86,
    manaBase: 420,
    manaScale: 25,
    armorBase: 40,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 64,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Pyke',
    title: 'The Bloodharbor Ripper',
    icon: '../images/portraits/PykeSquare.webp',
    rolePrim: roles.support,
    roleSecond: roles.middle,
    healthBase: 650,
    healthScale: 93,
    manaBase: 435,
    manaScale: 43,
    armorBase: 50,
    armorScale: 5,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 340,
    attackBase: 64,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.017
  },

  {
    name: 'Rakan',
    title: 'The Charmer',
    icon: '../images/portraits/RakanSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 540,
    healthScale: 78,
    manaBase: 435,
    manaScale: 46,
    armorBase: 40,
    armorScale: 4,
    magresBase: 34,
    magresScale: 1,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022
  },

  {
    name: 'Rammus',
    title: 'The Armordillo',
    icon: '../images/portraits/RammusSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 610,
    healthScale: 78,
    manaBase: 345,
    manaScale: 31,
    armorBase: 45,
    armorScale: 4,
    magresBase: 38,
    magresScale: 1,
    moveSpeed: 335,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Renekton',
    title: 'The Butcher of the Sands',
    icon: '../images/portraits/RenektonSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 650,
    healthScale: 93,
    manaBase: false,
    manaScale: 0,
    armorBase: 40,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 70,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Rengar',
    title: 'The Pridestalker',
    icon: '../images/portraits/RengarSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 650,
    healthScale: 78,
    manaBase: false,
    manaScale: 0,
    armorBase: 40,
    armorScale: 3,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.23,
    asScale: 0.667*0.022
  },

  {
    name: 'Riven',
    title: 'The Exile',
    icon: '../images/portraits/RivenSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 105,
    manaBase: false,
    manaScale: 0,
    armorBase: 40,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 345,
    attackBase: 64,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Samira',
    title: 'The Desert Rose',
    icon: '../images/portraits/SamiraSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 610,
    healthScale: 86,
    manaBase: 345,
    manaScale: 37,
    armorBase: 35,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 330,
    attackBase: 64,
    attackScale: 4,
    apBase: 0,
    asBase: 0.623,
    asBaseBonus: 0.623*0.3,
    asScale: 0.623*0.032
  },

  {
    name: 'Senna',
    title: 'The Redeemer',
    icon: '../images/portraits/SennaSquare.webp',
    rolePrim: roles.support,
    roleSecond: roles.duo,
    healthBase: 530,
    healthScale: 78,
    manaBase: 345,
    manaScale: 49,
    armorBase: 35,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 52,
    attackScale: 0,
    apBase: 0,
    asBase: 0.620,
    asBaseBonus: 0.620*0,
    asScale: 0.620*0.017
  },

  {
    name: 'Seraphine',
    title: 'The Starry-Eyed Songstress',
    icon: '../images/portraits/SeraphineSquare.webp',
    rolePrim: roles.support,
    roleSecond: roles.middle,
    healthBase: 530,
    healthScale: 78,
    manaBase: 435,
    manaScale: 37,
    armorBase: 30,
    armorScale: 4,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 330,
    attackBase: 52,
    attackScale: 2,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0
  },

  {
    name: 'Sett',
    title: 'The Boss',
    icon: '../images/portraits/SettSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.support,
    healthBase: 610,
    healthScale: 86,
    manaBase: false,
    manaScale: 0,
    armorBase: 35,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.664,
    asBaseBonus: 0.664*0.13,
    asScale: 0.664*0.012
  },

  {
    name: 'Shen',
    title: 'Eye of Twilight',
    icon: '../images/portraits/ShenSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 570,
    healthScale: 78,
    manaBase: false,
    manaScale: 0,
    armorBase: 40,
    armorScale: 3,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Shyvana',
    title: 'The Half-Dragon',
    icon: '../images/portraits/ShyvanaSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 610,
    healthScale: 112,
    manaBase: false,
    manaScale: 0,
    armorBase: 40,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.23,
    asScale: 0.667*0.022
  },

  {
    name: 'Singed',
    title: 'Mad Chemist',
    icon: '../images/portraits/SingedSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 610,
    healthScale: 78,
    manaBase: 345,
    manaScale: 37,
    armorBase: 40,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 64,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Sion',
    title: 'The Undead Juggernaut',
    icon: '../images/portraits/SionSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 570,
    healthScale: 71,
    manaBase: 345,
    manaScale: 37,
    armorBase: 40,
    armorScale: 3,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 64,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.012
  },

  {
    name: 'Sona',
    title: 'The Maven of the Strings',
    icon: '../images/portraits/SonaSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 530,
    healthScale: 78,
    manaBase: 345,
    manaScale: 37,
    armorBase: 35,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 335,
    attackBase: 46,
    attackScale: 2,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0
  },

  {
    name: 'Soraka',
    title: 'The Starchild',
    icon: '../images/portraits/SorakaSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 104,
    healthScale: 86,
    manaBase: 345,
    manaScale: 37,
    armorBase: 31,
    armorScale: 4,
    magresBase: 30,
    magresScale: 2,
    moveSpeed: 335,
    attackBase: 52,
    attackScale: 4,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0
  },

  {
    name: 'Swain',
    title: 'The Noxian Grand General',
    icon: '../images/portraits/SwainSquare.webp',
    rolePrim: roles.middle,
    roleSecond: roles.support,
    healthBase: 600,
    healthScale: 77,
    manaBase: 460,
    manaScale: 30,
    armorBase: 31,
    armorScale: 5,
    magresBase: 32,
    magresScale: 2,
    moveSpeed: 340,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022
  },

  {
    name: 'Teemo',
    title: 'The Swift Scout',
    icon: '../images/portraits/TeemoSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 570,
    healthScale: 78,
    manaBase: 345,
    manaScale: 31,
    armorBase: 30,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 52,
    attackScale: 3,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022
  },

  {
    name: 'Thresh',
    title: 'The Chain Warden',
    icon: '../images/portraits/ThreshSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 610,
    healthScale: 86,
    manaBase: 435,
    manaScale: 31,
    armorBase: 30,
    armorScale: 0,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 2,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022
  },

  {
    name: 'Tristana',
    title: 'The Megling Gunner',
    icon: '../images/portraits/TristanaSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 570,
    healthScale: 86,
    manaBase: 300,
    manaScale: 31,
    armorBase: 35,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 335,
    attackBase: 64,
    attackScale: 4,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.032
  },

  {
    name: 'Tryndamere',
    title: 'The Barbarian King',
    icon: '../images/portraits/TryndamereSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 93,
    manaBase: false,
    manaScale: 37,
    armorBase: 40,
    armorScale: 3,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 54,
    attackScale: 5,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.23,
    asScale: 0.667*0.022
  },

  {
    name: 'Twisted Fate',
    title: 'The Card Master',
    icon: '../images/portraits/Twisted_FateSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 86,
    manaBase: 345,
    manaScale: 31,
    armorBase: 30,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 345,
    attackBase: 52,
    attackScale: 4,
    apBase: 0,
    asBase: 0.626,
    asBaseBonus: 0.626*0.23,
    asScale: 0.626*0.022
  },

  {
    name: 'Twitch',
    title: 'The Olague Rat',
    icon: '../images/portraits/TwitchSquare.webp',
    rolePrim: roles.duo,
    roleSecond: roles.jungle,
    healthBase: 600,
    healthScale: 83,
    manaBase: 340,
    manaScale: 33,
    armorBase: 40,
    armorScale: 3,
    magresBase: 32,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.032
  },

  {
    name: 'Urgot',
    title: 'The Dreadnought',
    icon: '../images/portraits/UrgotSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 630,
    healthScale: 95,
    manaBase: 380,
    manaScale: 37,
    armorBase: 40,
    armorScale: 4,
    magresBase: 40,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022
  },

  {
    name: 'Varus',
    title: 'The Arrow of Retribution',
    icon: '../images/portraits/VarusSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 530,
    healthScale: 86,
    manaBase: 390,
    manaScale: 25,
    armorBase: 35,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.623,
    asBaseBonus: 0.623*0.3,
    asScale: 0.623*0.032
  },

  {
    name: 'Vayne',
    title: 'The Night Hunter',
    icon: '../images/portraits/VayneSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 540,
    healthScale: 78,
    manaBase: 331,
    manaScale: 37,
    armorBase: 31,
    armorScale: 4,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 335,
    attackBase: 58,
    attackScale: 2,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.022
  },

  {
    name: 'Veigar',
    title: 'The Tiny Master of Evil',
    icon: '../images/portraits/VeigarSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 78,
    manaBase: 480,
    manaScale: 37,
    armorBase: 35,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0
  },

  {
    name: 'Vex',
    title: 'The Gloomist',
    icon: '../images/portraits/VexSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 610,
    healthScale: 78,
    manaBase: 480,
    manaScale: 37,
    armorBase: 30,
    armorScale: 4,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 355,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0
  },

  {
    name: 'Vi',
    title: 'The Piltover Enforcer',
    icon: '../images/portraits/ViSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 650,
    healthScale: 78,
    manaBase: 390,
    manaScale: 37,
    armorBase: 30,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 64,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Vladimir',
    title: 'The Crimson Reaper',
    icon: '../images/portraits/VladimirSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.middle,
    healthBase: 570,
    healthScale: 86,
    manaBase: false,
    manaScale: 0,
    armorBase: 30,
    armorScale: 4,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 52,
    attackScale: 3,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022
  },

  {
    name: 'Volibear',
    title: 'The Relentless Storm',
    icon: '../images/portraits/VolibearSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 89,
    manaBase: 390,
    manaScale: 49,
    armorBase: 40,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 62,
    attackScale: 3,
    apBase: 0,
    asBase: 0.664,
    asBaseBonus: 0.664*0.1,
    asScale: 0.664*0.002
  },

  {
    name: 'Warwick',
    title: 'The Uncaged Wrath of Zaun',
    icon: '../images/portraits/WarwickSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 610,
    healthScale: 58,
    manaBase: 300,
    manaScale: 37,
    armorBase: 35,
    armorScale: 3,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.22,
    asScale: 0.667*0.022
  },

  {
    name: 'Wukong',
    title: 'The Monkey King',
    icon: '../images/portraits/WukongSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 78,
    manaBase: 345,
    manaScale: 31,
    armorBase: 35,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 64,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Xayah',
    title: 'The Rebel',
    icon: '../images/portraits/XayahSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 610,
    healthScale: 78,
    manaBase: 435,
    manaScale: 31,
    armorBase: 40,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 335,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.032
  },

  {
    name: 'Xin Zhao',
    title: 'The Seneschal of Demacia',
    icon: '../images/portraits/Xin_ZhaoSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 650,
    healthScale: 86,
    manaBase: 345,
    manaScale: 31,
    armorBase: 35,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 62,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.22,
    asScale: 0.667*0.022
  },

  {
    name: 'Yasuo',
    title: 'The Unforgiven',
    icon: '../images/portraits/YasuoSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 78,
    manaBase: false,
    manaScale: 0,
    armorBase: 35,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 62,
    attackScale: 4,
    apBase: 0,
    asBase: 0.669,
    asBaseBonus: 0.669*0.33,
    asScale: 0.669*0.032
  },

  {
    name: 'Yone',
    title: 'The Unforgotten',
    icon: '../images/portraits/YoneSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.middle,
    healthBase: 610,
    healthScale: 112,
    manaBase: false,
    manaScale: 0,
    armorBase: 35,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 345,
    attackBase: 54,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.23,
    asScale: 0.667*0.032
  },

  {
    name: 'Yuumi',
    title: 'The Magical Cat',
    icon: '../images/portraits/YuumiSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 530,
    healthScale: 71,
    manaBase: 435,
    manaScale: 37,
    armorBase: 35,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.007
  },

  {
    name: 'Zed',
    title: 'The Master of Shadows',
    icon: '../images/portraits/ZedSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 650,
    healthScale: 78,
    manaBase: false,
    manaScale: 0,
    armorBase: 35,
    armorScale: 4,
    magresBase: 38,
    magresScale: 2,
    moveSpeed: 355,
    attackBase: 64,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

  {
    name: 'Zeri',
    title: 'The Spark of Zaun',
    icon: '../images/portraits/ZeriSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 600,
    healthScale: 112,
    manaBase: 380,
    manaScale: 37,
    armorBase: 31,
    armorScale: 4,
    magresBase: 32,
    magresScale: 2,
    moveSpeed: 325,
    attackBase: 54,
    attackScale: 3,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.027
  },

  {
    name: 'Ziggs',
    title: 'The Helxplosives Expert',
    icon: '../images/portraits/ZiggsSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 78,
    manaBase: 460,
    manaScale: 31,
    armorBase: 30,
    armorScale: 3,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 52,
    attackScale: 3,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0
  },

  {
    name: 'Zoe',
    title: 'The Aspect of Twilight',
    icon: '../images/portraits/ZoeSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 83,
    manaBase: 420,
    manaScale: 37,
    armorBase: 31,
    armorScale: 3,
    magresBase: 32,
    magresScale: 1,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022
  },
]


export default champions;