const roles = {
baron: <span className="role"><img src="../images/laneIcons/laneBaron.webp" alt="Baron lane icon" /> Baron</span>,
jungle: <span className="role"><img src="../images/laneIcons/laneJungle.webp" alt="Jungle lane icon" /> Jungle</span>,
middle: <span className="role"><img src="../images/laneIcons/laneMiddle.webp" alt="Middle lane icon" /> Middle</span>,
duo: <span className="role"><img src="../images/laneIcons/laneDuo.webp" alt="Duo lane icon" /> Duo</span>,
support: <span className="role"><img src="../images/laneIcons/laneSupport.webp" alt="Support lane icon" /> Support</span>
}

const champions = [
 {
    id: 'aatrox',
    name: 'Aatrox',
    title: 'the Darkin Blade',
    icon: '../images/portraits/AatroxSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 600,
    healthScale: 128,
    manaBase: false,
    armorBase: 40,
    armorScale: 4.5,
    magresBase: 40,
    magresScale: 1.5,
    moveSpeed: 355,
    attackBase: 62,
    attackScale: 5.5,
    apBase: 0,
    asBase: 0.664,
    asBaseBonus: 0.664*0.1,
    asScale: 0.664*0.012,    
  },

{
    id: 'ahri',
    name: 'Ahri',
    title: 'The Nine-Tailed Fox',
    icon: '../images/portraits/AhriSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 530,
    healthScale: 105,
    manaBase: 435,
    manaScale: 49,
    armorBase: 30,
    armorScale: 3.9,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 345,
    attackBase: 52,
    attackScale: 3.6,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0
  },

{
    id:'akali',
    name: 'Akali',
    title: 'The Rogue Assasin',
    icon: '../images/portraits/AkaliSquare.webp',
    rolePrim: roles.middle,
    roleSecond: roles.baron,
    healthBase: 600,
    healthScale: 125,
    manaBase: false,
    manaScale: 0,
    armorBase: 34,
    armorScale: 3.64,
    magresBase: 38,
    magresScale: 2.35,
    moveSpeed: 355,
    attackBase: 64,
    attackScale: 4.57,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022
  },

{
    id:'akshan',
    name: 'Akshan',
    title: 'The Rogue Sentinel',
    icon: '../images/portraits/AkshanSquare.webp',
    rolePrim: roles.middle,
    roleSecond: roles.duo,
    healthBase: 570,
    healthScale: 115,
    manaBase: 390,
    manaScale: 49,
    armorBase: 35,
    armorScale: 3.93,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 340,
    attackBase: 52,
    attackScale: 5.5,
    apBase: 0,
    asBase: 0.5,
    asBaseBonus: 0.5*0.4,
    asScale: 0.5*0.007
  },

{
    name: 'Alistar',
    title: 'The Minotaur',
    icon: '../images/portraits/AlistarSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 610,
    healthScale: 135,
    manaBase: 345,
    manaScale: 41,
    armorBase: 45,
    armorScale: 4.7,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 340,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'alistar'
  },

{
    name: 'Amumu',
    title: 'The Sad Mummy',
    icon: '../images/portraits/AmumuSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: roles.support,
    healthBase: 650,
    healthScale: 95,
    manaBase: 390,
    manaScale: 65,
    armorBase: 35,
    armorScale: 3.93,
    magresBase: 38,
    magresScale: 0.86,
    moveSpeed: 345,
    attackBase: 52,
    attackScale: 3.4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'amumu'
  },

{
    name: 'Annie',
    title: 'The Dark Child',
    icon: '../images/portraits/AnnieSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 530,
    healthScale: 105,
    manaBase: 435,
    manaScale: 57,
    armorBase: 30,
    armorScale: 4.71,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 345,
    attackBase: 52,
    attackScale: 2.71,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0,
    id:'annie'
  },

{
    name: 'Ashe',
    title: 'The Frost Archer',
    icon: '../images/portraits/AsheSquare.webp',
    rolePrim: roles.duo,
    roleSecond: roles.support,
    healthBase: 570,
    healthScale: 115,
    manaBase: 345,
    manaScale: 33,
    armorBase: 35,
    armorScale: 3.9,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 335,
    attackBase: 58,
    attackScale: 2.7,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.667*0.33,
    asScale: 0.667*0.032,
    id:'ashe'
  },

  {
    name: 'Aurelion Sol',
    title: 'The Star Forger',
    icon: '../images/portraits/Aurelion_SolSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 115,
    manaBase: 435,
    manaScale: 57,
    armorBase: 30,
    armorScale: 3.9,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 335,
    attackBase: 52,
    attackScale: 2.7,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0,
    id:'aurelionsol'
  },

  {
    name: 'Blitzcrank',
    title: 'The Great Steam Golem',
    icon: '../images/portraits/BlitzcrankSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 650,
    healthScale: 115,
    manaBase: 300,
    manaScale: 41,
    armorBase: 50,
    armorScale: 5.1,
    magresBase: 38,
    magresScale: 1.6,
    moveSpeed: 335,
    attackBase: 58,
    attackScale: 1.7,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'blitzcrank'
  },

  {
    name: 'Brand',
    title: 'The Burning Vengeance',
    icon: '../images/portraits/BrandSquare.webp',
    rolePrim: roles.middle,
    roleSecond: roles.support,
    healthBase: 530,
    healthScale: 95,
    manaBase: 435,
    manaScale: 45,
    armorBase: 30,
    armorScale: 3.9,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 3.6,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0,
    id:'brand'
  },

  {
    name: 'Braum',
    title: 'The Heart of the Freljord',
    icon: '../images/portraits/BraumSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 610,
    healthScale: 115,
    manaBase: 300,
    manaScale: 49,
    armorBase: 46,
    armorScale: 5.14,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 345,
    attackBase: 54,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'braum'
  },

  {
    name: 'Caitlyn',
    title: 'The Sheriff of Piltover',
    icon: '../images/portraits/CaitlynSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 570,
    healthScale: (115),
    manaBase: 345,
    manaScale: 41,
    armorBase: 35,
    armorScale: 3.9,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 335,
    attackBase: 54,
    attackScale: 4,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.032,
    id:'caitlyn'
  },

  {
    name: 'Camille',
    title: 'The Steel Shadow',
    icon: '../images/portraits/CamilleSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 120,
    manaBase: 390,
    manaScale: 33,
    armorBase: 40,
    armorScale: 4.71,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 4.57,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.624*0.23,
    asScale: 0.667*0.022,
    id:'camille'
  },

  {
    name: 'Corki',
    title: 'The Daring Bombardier',
    icon: '../images/portraits/CorkiSquare.webp',
    rolePrim: roles.duo,
    roleSecond: roles.middle,
    healthBase: 570,
    healthScale: 112,
    manaBase: 435,
    manaScale: 50,
    armorBase: 35,
    armorScale: 4.5,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 335,
    attackBase: 54,
    attackScale: 4,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022,
    id:'corki'
  },

  {
    name: 'Darius',
    title: 'The Hand of Noxus',
    icon: '../images/portraits/DariusSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 610,
    healthScale: 136,
    manaBase: 345,
    manaScale: 41,
    armorBase: 45,
    armorScale: 5.14,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 350,
    attackBase: 70,
    attackScale: 5.5,
    apBase: 0,
    asBase: 0.664,
    asBaseBonus: 0.664*0.13,
    asScale: 0.664*0.012,
    id:'darius'
  },

  {
    name: 'Diana',
    title: 'The Scorn of the Moon',
    icon: '../images/portraits/DianaSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 600,
    healthScale: 125,
    manaBase: 435,
    manaScale: 41,
    armorBase: 40,
    armorScale: 4.36,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 52,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'diana'
  },

  {
    name: 'Dr. Mundo',
    title: 'The Madman of Zaun',
    icon: '../images/portraits/DrMundoSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 105,
    manaBase: false,
    manaScale: 0,
    armorBase: 35,
    armorScale: 3.9,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 58,
    attackScale: 4.6,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'drmundo'
  },

  {
    name: 'Draven',
    title: 'The Glorious Executioner',
    icon: '../images/portraits/DravenSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 610,
    healthScale: 115,
    manaBase: 480,
    manaScale: 65,
    armorBase: 35,
    armorScale: 4.4,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 340,
    attackBase: 66,
    attackScale: 4.5,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.032,
    id:'draven'
  },

  {
    name: 'Ekko',
    title: 'The Boy Who Shattered Time',
    icon: '../images/portraits/EkkoSquare.webp',
    rolePrim: roles.middle,
    roleSecond: roles.jungle,
    healthBase: 610,
    healthScale: 105,
    manaBase: 390,
    manaScale: 57,
    armorBase: 40,
    armorScale: 3.5,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'ekko'
  },

  {
    name: 'Evelynn',
    title: 'Agony\'s Embrace',
    icon: '../images/portraits/EvelynnSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 115,
    manaBase: 345,
    manaScale: 49,
    armorBase: 45,
    armorScale: 4.36,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 350,
    attackBase: 64,
    attackScale: 3.65,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'evelynn'
  },

  {
    name: 'Ezreal',
    title: 'The Prodigal Explorer',
    icon: '../images/portraits/EzrealSquare.webp',
    rolePrim: roles.duo,
    roleSecond: roles.middle,
    healthBase: 570,
    healthScale: 105,
    manaBase: 390,
    manaScale: 49,
    armorBase: 30,
    armorScale: 4.4,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 335,
    attackBase: 62,
    attackScale: 4,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.022,
    id:"ezreal"
  },

  {
    name: 'Fiddlesticks',
    title: 'The Ancient Fear',
    icon: '../images/portraits/Fiddlesticks.jpg',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 104,
    manaBase: 420,
    manaScale: 50,
    armorBase: 31,
    armorScale: 4,
    magresBase: 32,
    magresScale: 1,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 2.5,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022,
    id:"fiddlesticks"
  },

  {
    name: 'Fiora',
    title: 'The Grand Duelist',
    icon: '../images/portraits/FioraSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 610,
    healthScale: 115,
    manaBase: 300,
    manaScale: 49,
    armorBase: 40,
    armorScale: 4.36,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 70,
    attackScale: 4.57,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'fiora'
  },

  {
    name: 'Fizz',
    title: 'The Tidal Trickster',
    icon: '../images/portraits/FizzSquare.webp',
    rolePrim: roles.middle,
    roleSecond: roles.jungle,
    healthBase: 610,
    healthScale: 125,
    manaBase: 345,
    manaScale: 49,
    armorBase: 30,
    armorScale: 4.36,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'fizz'
  },

  {
    name: 'Galio',
    title: 'The Colossus',
    icon: '../images/portraits/GalioSquare.webp',
    rolePrim: roles.middle,
    roleSecond: roles.support,
    healthBase: 600,
    healthScale: 135,
    manaBase: 435,
    manaScale: 33,
    armorBase: 34,
    armorScale: 3.93,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'galio'
  },

  {
    name: 'Garen',
    title: 'The Might of Demacia',
    icon: '../images/portraits/GarenSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 650,
    healthScale: 125,
    manaBase: false,
    manaScale: 0,
    armorBase: 45,
    armorScale: 5.8,
    magresBase: 38,
    magresScale: 2.64,
    moveSpeed: 350,
    attackBase: 64,
    attackScale: 5.5,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'garen'
  },

  {
    name: 'Gragas',
    title: 'The Rabble Rouser',
    icon: '../images/portraits/GragasSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 125,
    manaBase: 390,
    manaScale: 59,
    armorBase: 40,
    armorScale: 4.3,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 340,
    attackBase: 70,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'gragas'
  },

  {
    name: 'Graves',
    title: 'The Outlaw',
    icon: '../images/portraits/GravesSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: roles.baron,
    healthBase: 570,
    healthScale: 115,
    manaBase: 390,
    manaScale: 49,
    armorBase: 35,
    armorScale: 3.9,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 350,
    attackBase: 64,
    attackScale: 3.64,
    apBase: 0,
    asBase: 1,
    asBaseBonus: 1*0.03,
    asScale: 1*0.022,
    id:'graves'
  },

  {
    name: 'Gwen',
    title: 'The Hallowed Seamstress',
    icon: '../images/portraits/GwenSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 660,
    healthScale: 116,
    manaBase: 345,
    manaScale: 41,
    armorBase: 45,
    armorScale: 4.7,
    magresBase: 38,
    magresScale: 1.6,
    moveSpeed: 340,
    attackBase: 58,
    attackScale: 3.6,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.23,
    asScale: 0.667*0.022,
    id:'gwen'
  },
  
  {
    name: 'Hecarim',
    title: 'The Shadow of War',
    icon: '../images/portraits/HecarimSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 600,
    healthScale: 120,
    manaBase: 380,
    manaScale: 57,
    armorBase: 37,
    armorScale: 4.5,
    magresBase: 36,
    magresScale: 1.5,
    moveSpeed: 350,
    attackBase: 54,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'hecarim'
  },
  
  {
    name: 'Irelia',
    title: 'The Blade Dancer',
    icon: '../images/portraits/IreliaSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.middle,
    healthBase: 650,
    healthScale: 118,
    manaBase: 345,
    manaScale: 33,
    armorBase: 40,
    armorScale: 3.9,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 4.6,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'irelia'
  },

  {
    name: 'Janna',
    title: 'The Storm\'s Fury',
    icon: '../images/portraits/JannaSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 570,
    healthScale: 95,
    manaBase: 435,
    manaScale: 57,
    armorBase: 42,
    armorScale: 4.36,
    magresBase: 35,
    magresScale: 0.86,
    moveSpeed: 340,
    attackBase: 52,
    attackScale: 2.71,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0,
    id:"janna"
  },


  {
    name: 'Jarvan IV',
    title: 'The Exemplar of Demacia',
    icon: '../images/portraits/JarvanIVSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 650,
    healthScale: 115,
    manaBase: 390,
    manaScale: 41,
    armorBase: 40,
    armorScale: 4.36,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 4.55,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'jarvaniv'
  },  
  
  {
    name: 'Jax',
    title: 'Grandmaster at Arms',
    icon: '../images/portraits/JaxSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 112,
    manaBase: 390,
    manaScale: 57,
    armorBase: 40,
    armorScale: 3.92,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 58,
    attackScale: 4.57,
    apBase: 0,
    asBase: 0.664,
    asBaseBonus: 0.664*0.13,
    asScale: 0.664*0.022,
    id:'jax'
  },

  {
    name: 'Jayce',
    title: 'The Defender of Tomorrow',
    icon: '../images/portraits/JayceSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.middle,
    healthBase: 610,
    healthScale: 112,
    manaBase: 345,
    manaScale: 57,
    armorBase: 45,
    armorScale: 6.4,
    magresBase: 35,
    magresScale: 2.9,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 4.6,
    apBase: 0,
    asBase: 0.669,
    asBaseBonus: 0.669*0.36,
    asScale: 0.669*0.032,
    id:'jayce'
  },

  {
    name: 'Jhin',
    title: 'The Virtuoso',
    icon: '../images/portraits/JhinSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 570,
    healthScale: 115,
    manaBase: 390,
    manaScale: 57,
    armorBase: 35,
    armorScale: 3.9,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 340,
    attackBase: 58,
    attackScale: 4.57,
    apBase: 0,
    asBase: 0.629,
    asBaseBonus: 0.629*0.05,
    asScale: 0.629*0.032,
    id:'jhin'
  },

  {
    name: 'Jinx',
    title: 'The Loose Cannon',
    icon: '../images/portraits/JinxSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 610,
    healthScale: 105,
    manaBase: 345,
    manaScale: 49,
    armorBase: 35,
    armorScale: 4.4,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 335,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.017,
    id:'jinx'
  },

  {
    name: 'Kai\'Sa',
    title: 'Daughter of the Void',
    icon: '../images/portraits/KaisaSquare.webp',
    rolePrim: roles.duo,
    roleSecond: roles.middle,
    healthBase: 570,
    healthScale: 115,
    manaBase: 435,
    manaScale: 41,
    armorBase: 35,
    armorScale: 3.5,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 340,
    attackBase: 62,
    attackScale: 3.5,
    apBase: 0,
    asBase: 0.626,
    asBaseBonus: 0.626*0.23,
    asScale: 0.626*0.032,
    id:'kaisa'
  },

  {
    name: 'Karma',
    title: 'The Enlightened One',
    icon: '../images/portraits/KarmaSquare.webp',
    rolePrim: roles.support,
    roleSecond: roles.middle,
    healthBase: 570,
    healthScale: 125,
    manaBase: 390,
    manaScale: 57,
    armorBase: 35,
    armorScale: 4.71,
    magresBase: 32,
    magresScale: 0.86,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022,
    id:'karma'
  },

  {
    name: 'Kassadin',
    title: 'The Void Walker',
    icon: '../images/portraits/KassadinSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 600,
    healthScale: 105,
    manaBase: 480,
    manaScale: 65,
    armorBase: 30,
    armorScale: 3.93,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 4.57,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'kassadin'
  },

  {
    name: 'Katarina',
    title: 'The Sinister Blade',
    icon: '../images/portraits/KatarinaSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 115,
    manaBase: false,
    manaScale: 0,
    armorBase: 30,
    armorScale: 4.36,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'katarina'
  },

  {
    name: 'Kayle',
    title: 'The Righteous',
    icon: '../images/portraits/KayleSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.middle,
    healthBase: 570,
    healthScale: 95,
    manaBase: 345,
    manaScale: 41,
    armorBase: 30,
    armorScale: 3.3,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 345,
    attackBase: 52,
    attackScale: 2.7,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.23,
    asScale: 0.667*0.022,
    id:'kayle'
  },

  {
    name: 'Kayn',
    title: 'The Shadow Assasin',
    icon: '../images/portraits/KaynSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 600,
    healthScale: 112,
    manaBase: 420,
    manaScale: 60,
    armorBase: 37,
    armorScale: 4.5,
    magresBase: 36,
    magresScale: 1.5,
    moveSpeed: 350,
    attackBase: 70,
    attackScale: 4,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'kayn'
  },

  {
    name: 'Kennen',
    title: 'The Heart of the Tempest',
    icon: '../images/portraits/KennenSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.middle,
    healthBase: 610,
    healthScale: 105,
    manaBase: false,
    manaScale: 50,
    armorBase: 40,
    armorScale: 4.35,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022,
    id:'kennen'
  },

  {
    name: 'Kha\'Zix',
    title: 'The Voidreaver',
    icon: '../images/portraits/Kha\'ZixSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 610,
    healthScale: 105,
    manaBase: 390,
    manaScale: 49,
    armorBase: 35,
    armorScale: 3.9,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 54,
    attackScale: 4.57,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'khazix'
  },

  {
    name: 'Lee Sin',
    title: 'The Blind Monk',
    icon: '../images/portraits/Lee_SinSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 650,
    healthScale: 105,
    manaBase: false,
    manaScale: 50,
    armorBase: 35,
    armorScale: 4.7,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 66,
    attackScale: 4.57,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'leesin'
  },

  {
    name: 'Leona',
    title: 'The Radiant Dawn',
    icon: '../images/portraits/LeonaSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 690,
    healthScale: 105,
    manaBase: 390,
    manaScale: 41,
    armorBase: 50,
    armorScale: 4.7,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 345,
    attackBase: 62,
    attackScale: 3,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.012,
    id:'leona'
  },

  {
    name: 'Lillia',
    title: 'The Bashful Bloom',
    icon: '../images/portraits/LilliaSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 104,
    manaBase: 420,
    manaScale: 50,
    armorBase: 34,
    armorScale: 4,
    magresBase: 32,
    magresScale: 1,
    moveSpeed: 350,
    attackBase: 62,
    attackScale: 2.5,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022,
    id:'lillia'
  },

  {
    name: 'Lucian',
    title: 'The Purifier',
    icon: '../images/portraits/LucianSquare.webp',
    rolePrim: roles.duo,
    roleSecond: roles.middle,
    healthBase: 610,
    healthScale: 115,
    manaBase: 390,
    manaScale: 49,
    armorBase: 35,
    armorScale: 3.9,
    magresBase: 30,
    magresScale: 0.8,
    moveSpeed: 345,
    attackBase: 64,
    attackScale: 4,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.032,
    id:'lucian'
  },

  {
    name: 'Lulu',
    title: 'The Fae Sorceress',
    icon: '../images/portraits/LuluSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 530,
    healthScale: 95,
    manaBase: 480,
    manaScale: 57,
    armorBase: 34,
    armorScale: 4.36,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 345,
    attackBase: 46,
    attackScale: 2.71,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0,
    id:'lulu'
  },

  {
    name: 'Lux',
    title: 'The Lady of Luminosity',
    icon: '../images/portraits/LuxSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 530,
    healthScale: 105,
    manaBase: 480,
    manaScale: 49,
    armorBase: 30,
    armorScale: 4.71,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 350,
    attackBase: 52,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.6625*0,
    id:'lux'
  },

  {
    name: 'Malphite',
    title: 'Shard of the Monolith',
    icon: '../images/portraits/MalphiteSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 650,
    healthScale: 115,
    manaBase: 345,
    manaScale: 41,
    armorBase: 45,
    armorScale: 4.36,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 350,
    attackBase: 52,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'malphite'
  },

  {
    name: 'Master Yi',
    title: 'The Wuju Bladesman',
    icon: '../images/portraits/Master_YiSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 610,
    healthScale: 105,
    manaBase: 345,
    manaScale: 49,
    armorBase: 40,
    armorScale: 3.9,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 54,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.82,
    asScale: 0.014285714,
    id:'masteryi'
  },

  {
    name: 'Miss Fortune',
    title: 'The Bounty Hunter',
    icon: '../images/portraits/MissFortuneSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 570,
    healthScale: 115,
    manaBase: 420,
    manaScale: 50,
    armorBase: 34,
    armorScale: 4,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 335,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.623,
    asBaseBonus: 0.623*0.3,
    asScale: 0.623*0.032,
    id:'missfortune'
  },

  {
    name: 'Morgana',
    title: 'The Fallen',
    icon: '../images/portraits/MorganaSquare.webp',
    rolePrim: roles.support,
    roleSecond: roles.middle,
    healthBase: 570,
    healthScale: 105,
    manaBase: 435,
    manaScale: 49,
    armorBase: 35,
    armorScale: 3.9,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 2.7,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022,
    id:'morgana'
  },

  {
    name: 'Nami',
    title: 'The Tidecaller',
    icon: '../images/portraits/NamiSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 570,
    healthScale: 95,
    manaBase: 390,
    manaScale: 49,
    armorBase: 35,
    armorScale: 4.71,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 350,
    attackBase: 52,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0,
    id:'nami'
  },

  {
    name: 'Nasus',
    title: 'The Curator of the Sands',
    icon: '../images/portraits/NasusSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 610,
    healthScale: 115,
    manaBase: 390,
    manaScale: 49,
    armorBase: 40,
    armorScale: 4.36,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 66,
    attackScale: 4.57,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'nasus'
  },

  {
    name: 'Nautilus',
    title: 'The Titan of the Depths',
    icon: '../images/portraits/NautilusSquare.webp',
    rolePrim: roles.support,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 115,
    manaBase: 390,
    manaScale: 57,
    armorBase: 40,
    armorScale: 4.36,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 340,
    attackBase: 58,
    attackScale: 4.57,
    apBase: 0,
    asBase: 0.664,
    asBaseBonus: 0.664*0.1,
    asScale: 0.664*0.012,
    id:'nautilus'
  },

  {
    name: 'Nilah',
    title: 'The Joy Unbound',
    icon: '../images/portraits/NilahSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 570,
    healthScale: 112,
    manaBase: 340,
    manaScale: 50,
    armorBase: 37,
    armorScale: 4.5,
    magresBase: 32,
    magresScale: 2,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.669,
    asBaseBonus: 0.669*0.33,
    asScale: 0.669*0.032,
    id:'nilah'
  },

  {
    name: 'Nunu & Willump',
    title: 'The Boy and His Yeti',
    icon: '../images/portraits/Nunu_WillumpSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 610,
    healthScale: 112,
    manaBase: 345,
    manaScale: 41,
    armorBase: 35,
    armorScale: 3.9,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 350,
    attackBase: 64,
    attackScale: 3.6,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'nunu'
  },

  {
    name: 'Olaf',
    title: 'The Berserker',
    icon: '../images/portraits/OlafSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: roles.baron,
    healthBase: 650,
    healthScale: 105,
    manaBase: 340,
    manaScale: 33,
    armorBase: 35,
    armorScale: 3.93,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 64,
    attackScale: 4.55,
    apBase: 0,
    asBase: 0.664,
    asBaseBonus: 0.664*0.1,
    asScale: 0.664*0.022,
    id:'olaf'
  },

  {
    name: 'Orianna',
    title: 'The Lady of Clockwork',
    icon: '../images/portraits/OriannaSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 530,
    healthScale: 104,
    manaBase: 435,
    manaScale: 57,
    armorBase: 25,
    armorScale: 3.5,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 335,
    attackBase: 46,
    attackScale: 2.7,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0,
    id:'orianna'
  },

  {
    name: 'Ornn',
    title: 'The Fire Below the Mountain',
    icon: '../images/portraits/OrnnSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.support,
    healthBase: 660,
    healthScale: 112,
    manaBase: 380,
    manaScale: 60,
    armorBase: 40,
    armorScale: 5,
    magresBase: 40,
    magresScale: 1.5,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.664,
    asBaseBonus: 0.664*0.1,
    asScale: 0.664*0.012,
    id:'ornn'
  },

  {
    name: 'Pantheon',
    title: 'The Unbreakable Spear',
    icon: '../images/portraits/PantheonSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 115,
    manaBase: 420,
    manaScale: 33,
    armorBase: 40,
    armorScale: 4.7,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 64,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'pantheon'
  },

  {
    name: 'Pyke',
    title: 'The Bloodharbor Ripper',
    icon: '../images/portraits/PykeSquare.webp',
    rolePrim: roles.support,
    roleSecond: roles.middle,
    healthBase: 650,
    healthScale: 125,
    manaBase: 435,
    manaScale: 57,
    armorBase: 50,
    armorScale: 5,
    magresBase: 38,
    magresScale: 2.5,
    moveSpeed: 340,
    attackBase: 64,
    attackScale: 3.5,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.017,
    id:'pyke'
  },

  {
    name: 'Rakan',
    title: 'The Charmer',
    icon: '../images/portraits/RakanSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 540,
    healthScale: 105,
    manaBase: 435,
    manaScale: 57,
    armorBase: 40,
    armorScale: 4.36,
    magresBase: 34,
    magresScale: 1.2,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022,
    id:'rakan'
  },

  {
    name: 'Rammus',
    title: 'The Armordillo',
    icon: '../images/portraits/RammusSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 610,
    healthScale: 105,
    manaBase: 345,
    manaScale: 41,
    armorBase: 45,
    armorScale: 4.7,
    magresBase: 38,
    magresScale: 0.8,
    moveSpeed: 335,
    attackBase: 58,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'rammus'
  },

  {
    name: 'Renekton',
    title: 'The Butcher of the Sands',
    icon: '../images/portraits/RenektonSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 650,
    healthScale: 125,
    manaBase: false,
    manaScale: 0,
    armorBase: 40,
    armorScale: 471,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 70,
    attackScale: 4.55,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'renekton'
  },

  {
    name: 'Rengar',
    title: 'The Pridestalker',
    icon: '../images/portraits/RengarSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 650,
    healthScale: 105,
    manaBase: false,
    manaScale: 0,
    armorBase: 40,
    armorScale: 3.9,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 58,
    attackScale: 3.6,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.23,
    asScale: 0.667*0.022,
    id:'rengar'
  },

  {
    name: 'Riven',
    title: 'The Exile',
    icon: '../images/portraits/RivenSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 115,
    manaBase: false,
    manaScale: 0,
    armorBase: 40,
    armorScale: 4.5,
    magresBase: 38,
    magresScale: 1.5,
    moveSpeed: 345,
    attackBase: 64,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'riven'
  },

  {
    name: 'Samira',
    title: 'The Desert Rose',
    icon: '../images/portraits/SamiraSquare.png',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 610,
    healthScale: 115,
    manaBase: 345,
    manaScale: 49,
    armorBase: 35,
    armorScale: 4.5,
    magresBase: 30,
    magresScale: 1,
    moveSpeed: 330,
    attackBase: 64,
    attackScale: 4,
    apBase: 0,
    asBase: 0.623,
    asBaseBonus: 0.623*0.3,
    asScale: 0.623*0.032,
    id:'samira'
  },

  {
    name: 'Senna',
    title: 'The Redeemer',
    icon: '../images/portraits/SennaSquare.webp',
    rolePrim: roles.support,
    roleSecond: roles.duo,
    healthBase: 530,
    healthScale: 105,
    manaBase: 345,
    manaScale: 65,
    armorBase: 35,
    armorScale: 3.9,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 340,
    attackBase: 52,
    attackScale: 0,
    apBase: 0,
    asBase: 0.620,
    asBaseBonus: 0.620*0,
    asScale: 0.620*0.017,
    id:'senna'
  },

  {
    name: 'Seraphine',
    title: 'The Starry-Eyed Songstress',
    icon: '../images/portraits/SeraphineSquare.webp',
    rolePrim: roles.support,
    roleSecond: roles.middle,
    healthBase: 530,
    healthScale: 105,
    manaBase: 435,
    manaScale: 49,
    armorBase: 30,
    armorScale: 4.71,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 350,
    attackBase: 52,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0,
    id:'seraphine'
  },

  {
    name: 'Sett',
    title: 'The Boss',
    icon: '../images/portraits/SettSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.support,
    healthBase: 610,
    healthScale: 115,
    manaBase: false,
    manaScale: 0,
    armorBase: 35,
    armorScale: 4.7,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 3.6,
    apBase: 0,
    asBase: 0.664,
    asBaseBonus: 0.664*0.13,
    asScale: 0.664*0.012,
    id:'sett'
  },

  {
    name: 'Shen',
    title: 'Eye of Twilight',
    icon: '../images/portraits/ShenSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 570,
    healthScale: 105,
    manaBase: false,
    manaScale: 0,
    armorBase: 40,
    armorScale: 3.9,
    magresBase: 38,
    magresScale: 1.6,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 4.6,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'shen'
  },

  {
    name: 'Shyvana',
    title: 'The Half-Dragon',
    icon: '../images/portraits/ShyvanaSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 610,
    healthScale: 112,
    manaBase: false,
    manaScale: 0,
    armorBase: 40,
    armorScale: 4.4,
    magresBase: 38,
    magresScale: 1.6,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 4.6,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.23,
    asScale: 0.667*0.022,
    id:'shyvana'
  },

  {
    name: 'Singed',
    title: 'Mad Chemist',
    icon: '../images/portraits/SingedSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 610,
    healthScale: 105,
    manaBase: 345,
    manaScale: 49,
    armorBase: 40,
    armorScale: 4.71,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 64,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'singed'
  },

  {
    name: 'Sion',
    title: 'The Undead Juggernaut',
    icon: '../images/portraits/SionSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 570,
    healthScale: 95,
    manaBase: 345,
    manaScale: 49,
    armorBase: 40,
    armorScale: 3.5,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 64,
    attackScale: 4.64,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.012,
    id:'sion'
  },

  {    
    name: 'Sivir',
    title: 'The Battle Mistress',
    icon: '../images/portraits/SivirSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 570,
    healthScale: 112,
    manaBase: 340,
    manaScale: 60,
    armorBase: 34,
    armorScale: 4,
    magresBase: 28,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.623,
    asBaseBonus: 0.623*0.3,
    asScale: 0.623*0.032,
    id:'sivir'    
  },

  {
    name: 'Sona',
    title: 'The Maven of the Strings',
    icon: '../images/portraits/SonaSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 530,
    healthScale: 96,
    manaBase: 345,
    manaScale: 49,
    armorBase: 35,
    armorScale: 3.9,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 340,
    attackBase: 46,
    attackScale: 2.7,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0,
    id:'sona'
  },

  {
    name: 'Soraka',
    title: 'The Starchild',
    icon: '../images/portraits/SorakaSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 570,
    healthScale: 104,
    manaBase: 345,
    manaScale: 65,
    armorBase: 31,
    armorScale: 4,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 340,
    attackBase: 52,
    attackScale: 1.71,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0,
    id:'soraka'
  },

  {
    name: 'Swain',
    title: 'The Noxian Grand General',
    icon: '../images/portraits/SwainSquare.webp',
    rolePrim: roles.middle,
    roleSecond: roles.support,
    healthBase: 600,
    healthScale: 77,
    manaBase: 460,
    manaScale: 30,
    armorBase: 31,
    armorScale: 5,
    magresBase: 32,
    magresScale: 2,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 3,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022,
    id:'swain'
  },

  {
    id: 'syndra',
    name: 'Syndra',
    title: 'the Dark Sovereign',
    icon: '../images/portraits/SyndraSquare.jpg',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 540,
    healthScale: 96,
    manaBase: 380,
    manaScale: 50,
    armorBase: 34,
    armorScale: 4,
    magresBase: 32,
    magresScale: 1,
    moveSpeed: 355,
    attackBase: 54,
    attackScale: 3,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0,    
  },

  {
    name: 'Teemo',
    title: 'The Swift Scout',
    icon: '../images/portraits/TeemoSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 570,
    healthScale: 105,
    manaBase: 345,
    manaScale: 41,
    armorBase: 30,
    armorScale: 3.9,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 345,
    attackBase: 52,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022,
    id:'teemo'
  },

  {
    name: 'Thresh',
    title: 'The Chain Warden',
    icon: '../images/portraits/ThreshSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 610,
    healthScale: 115,
    manaBase: 435,
    manaScale: 41,
    armorBase: 30,
    armorScale: 0,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 2.7,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022,
    id:'thresh'
  },

  {
    name: 'Tristana',
    title: 'The Megling Gunner',
    icon: '../images/portraits/TristanaSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 570,
    healthScale: 115,
    manaBase: 300,
    manaScale: 41,
    armorBase: 35,
    armorScale: 3.5,
    magresBase: 30,
    magresScale: 0.9,
    moveSpeed: 335,
    attackBase: 64,
    attackScale: 5,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.032,
    id:'tristana'
  },

  {
    name: 'Tryndamere',
    title: 'The Barbarian King',
    icon: '../images/portraits/TryndamereSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 125,
    manaBase: false,
    manaScale: 0,
    armorBase: 40,
    armorScale: 3.93,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 54,
    attackScale: 5.5,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.23,
    asScale: 0.667*0.022,
    id:'tryndamere'
  },

  {
    name: 'Twisted Fate',
    title: 'The Card Master',
    icon: '../images/portraits/Twisted_FateSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 115,
    manaBase: 345,
    manaScale: 41,
    armorBase: 30,
    armorScale: 3.5,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 345,
    attackBase: 52,
    attackScale: 2.71,
    apBase: 0,
    asBase: 0.626,
    asBaseBonus: 0.626*0.23,
    asScale: 0.626*0.022,
    id:'twistedfate'
  },

  {
    name: 'Twitch',
    title: 'The Plague Rat',
    icon: '../images/portraits/TwitchSquare.webp',
    rolePrim: roles.duo,
    roleSecond: roles.jungle,
    healthBase: 600,
    healthScale: 112,
    manaBase: 340,
    manaScale: 50,
    armorBase: 40,
    armorScale: 4,
    magresBase: 32,
    magresScale: 1,
    moveSpeed: 340,
    attackBase: 58,
    attackScale: 4.5,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.032,
    id:'twitch'
  },

  {
    name: 'Urgot',
    title: 'The Dreadnought',
    icon: '../images/portraits/UrgotSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 630,
    healthScale: 128,
    manaBase: 380,
    manaScale: 50,
    armorBase: 40,
    armorScale: 5,
    magresBase: 40,
    magresScale: 1.5,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 4.5,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022,
    id:'urgot'
  },

  {
    name: 'Varus',
    title: 'The Arrow of Retribution',
    icon: '../images/portraits/VarusSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 530,
    healthScale: 115,
    manaBase: 390,
    manaScale: 33,
    armorBase: 35,
    armorScale: 3.93,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 340,
    attackBase: 58,
    attackScale: 3.6,
    apBase: 0,
    asBase: 0.623,
    asBaseBonus: 0.623*0.3,
    asScale: 0.623*0.032,
    id:'varus'
  },

  {
    name: 'Vayne',
    title: 'The Night Hunter',
    icon: '../images/portraits/VayneSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 540,
    healthScale: 105,
    manaBase: 331,
    manaScale: 41,
    armorBase: 31,
    armorScale: 4.4,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 335,
    attackBase: 58,
    attackScale: 2.7,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.022,
    id:'vayne'
  },

  {
    name: 'Veigar',
    title: 'The Tiny Master of Evil',
    icon: '../images/portraits/VeigarSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 105,
    manaBase: 480,
    manaScale: 49,
    armorBase: 35,
    armorScale: 3.5,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 3.6,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0,
    id:'veigar'
  },

  {
    name: 'Vex',
    title: 'The Gloomist',
    icon: '../images/portraits/VexSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 610,
    healthScale: 105,
    manaBase: 480,
    manaScale: 49,
    armorBase: 30,
    armorScale: 4.4,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 3.6,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0,
    id:'vex'
  },

  {
    name: 'Vi',
    title: 'The Piltover Enforcer',
    icon: '../images/portraits/ViSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 650,
    healthScale: 105,
    manaBase: 390,
    manaScale: 49,
    armorBase: 34,
    armorScale: 5.14,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 350,
    attackBase: 64,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'vi'
  },

  {
    name: 'Vladimir',
    title: 'The Crimson Reaper',
    icon: '../images/portraits/VladimirSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.middle,
    healthBase: 570,
    healthScale: 115,
    manaBase: false,
    manaScale: 0,
    armorBase: 30,
    armorScale: 4.36,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 345,
    attackBase: 52,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022,
    id:'vladimir'
  },

  {
    name: 'Volibear',
    title: 'The Relentless Storm',
    icon: '../images/portraits/VolibearSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 120,
    manaBase: 390,
    manaScale: 65,
    armorBase: 40,
    armorScale: 4.71,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 350,
    attackBase: 62,
    attackScale: 4,
    apBase: 0,
    asBase: 0.664,
    asBaseBonus: 0.664*0.1,
    asScale: 0.664*0.002,
    id:'volibear'
  },

  {
    name: 'Warwick',
    title: 'The Uncaged Wrath of Zaun',
    icon: '../images/portraits/WarwickSquare.webp',
    rolePrim: roles.jungle,
    roleSecond: false,
    healthBase: 610,
    healthScale: 105,
    manaBase: 300,
    manaScale: 49,
    armorBase: 35,
    armorScale: 3.93,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 345,
    attackBase: 58,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.22,
    asScale: 0.667*0.022,
    id:'warwick'
  },

  {
    name: 'Wukong',
    title: 'The Monkey King',
    icon: '../images/portraits/WukongSquare.webp',
    rolePrim: roles.baron,
    roleSecond: roles.jungle,
    healthBase: 650,
    healthScale: 105,
    manaBase: 345,
    manaScale: 41,
    armorBase: 35,
    armorScale: 4.36,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 350,
    attackBase: 64,
    attackScale: 4.67,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'wukong'
  },

  {
    name: 'Xayah',
    title: 'The Rebel',
    icon: '../images/portraits/XayahSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 610,
    healthScale: 105,
    manaBase: 435,
    manaScale: 41,
    armorBase: 40,
    armorScale: 3.5,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 335,
    attackBase: 58,
    attackScale: 4,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.032,
    id:'xayah'
  },

  {
    name: 'Xin Zhao',
    title: 'The Seneschal of Demacia',
    icon: '../images/portraits/Xin_ZhaoSquare.webp',
    rolePrim: roles.baron,
    roleSecond: false,
    healthBase: 650,
    healthScale: 115,
    manaBase: 345,
    manaScale: 41,
    armorBase: 35,
    armorScale: 4.3,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 62,
    attackScale: 4.5,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.22,
    asScale: 0.667*0.022,
    id:'xinzhao'
  },

  {
    name: 'Yasuo',
    title: 'The Unforgiven',
    icon: '../images/portraits/YasuoSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 105,
    manaBase: false,
    manaScale: 0,
    armorBase: 35,
    armorScale: 4.36,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 62,
    attackScale: 4.5,
    apBase: 0,
    asBase: 0.669,
    asBaseBonus: 0.669*0.33,
    asScale: 0.669*0.032,
    id:'yasuo'   
  },

  {
    name: 'Yone',
    title: 'The Unforgotten',
    icon: '../images/portraits/YoneSquare.png',
    rolePrim: roles.baron,
    roleSecond: roles.middle,
    healthBase: 610,
    healthScale: 112,
    manaBase: false,
    manaScale: 0,
    armorBase: 40,
    armorScale: 4.4,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 345,
    attackBase: 54,
    attackScale: 3.6,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.23,
    asScale: 0.667*0.032,
    id:'yone' 
  },

  {
    name: 'Yuumi',
    title: 'The Magical Cat',
    icon: '../images/portraits/YuumiSquare.webp',
    rolePrim: roles.support,
    roleSecond: false,
    healthBase: 530,
    healthScale: 59,
    manaBase: 435,
    manaScale: 49,
    armorBase: 35,
    armorScale: 3.9,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 340,
    attackBase: 58,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.007,
    id:'yuumi'
  },

  {
    name: 'Zed',
    title: 'The Master of Shadows',
    icon: '../images/portraits/ZedSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 650,
    healthScale: 105,
    manaBase: false,
    manaScale: 0,
    armorBase: 35,
    armorScale: 4.36,
    magresBase: 38,
    magresScale: 1.64,
    moveSpeed: 355,
    attackBase: 64,
    attackScale: 4.75,
    apBase: 0,
    asBase: 0.667,
    asBaseBonus: 0.667*0.2,
    asScale: 0.667*0.022,
    id:'zed'
  },

  {
    name: 'Zeri',
    title: 'The Spark of Zaun',
    icon: '../images/portraits/ZeriSquare.webp',
    rolePrim: roles.duo,
    roleSecond: false,
    healthBase: 600,
    healthScale: 112,
    manaBase: 380,
    manaScale: 50,
    armorBase: 31,
    armorScale: 4.5,
    magresBase: 32,
    magresScale: 1.5,
    moveSpeed: 325,
    attackBase: 54,
    attackScale: 3.5,
    apBase: 0,
    asBase: 0.624,
    asBaseBonus: 0.624*0.33,
    asScale: 0.624*0.027,
    id:'zeri'
  },

  {
    name: 'Ziggs',
    title: 'The Helxplosives Expert',
    icon: '../images/portraits/ZiggsSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 105,
    manaBase: 460,
    manaScale: 41,
    armorBase: 30,
    armorScale: 3.5,
    magresBase: 30,
    magresScale: 0.86,
    moveSpeed: 345,
    attackBase: 52,
    attackScale: 3.64,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0,
    id:'ziggs'
  },

  {
    name: 'Zoe',
    title: 'The Aspect of Twilight',
    icon: '../images/portraits/ZoeSquare.webp',
    rolePrim: roles.middle,
    roleSecond: false,
    healthBase: 570,
    healthScale: 112,
    manaBase: 420,
    manaScale: 50,
    armorBase: 31,
    armorScale: 4,
    magresBase: 32,
    magresScale: 1,
    moveSpeed: 350,
    attackBase: 58,
    attackScale: 3.5,
    apBase: 0,
    asBase: 0.625,
    asBaseBonus: 0.625*0.2,
    asScale: 0.625*0.022,
    id:'zoe'
  },

  {
    name: 'Zyra',
    title: 'The Queen of Thorns',
    icon: '../images/portraits/ZyraSquare.png',
    rolePrim: roles.middle,
    roleSecond: roles.support,
    healthBase: 540,
    healthScale: 104,
    manaBase: 420,
    manaScale: 50,
    armorBase: 31,
    armorScale: 4,
    magresBase: 32,
    magresScale: 1.5,
    moveSpeed: 350,
    attackBase: 54,
    attackScale: 3.5,
    apBase: 0,
    asBase: 0.8,
    asBaseBonus: 0.8*0.2,
    asScale: 0.8*0,
    id:'zyra'
  },
]


export default champions;